onlinecourse/models.py
import sys
from django.utils.timezone import now
try:
    from django.db import models
except Exception:
    print("There was an error loading django modules. Do you have django installed?")
    sys.exit()

from django.conf import settings
import uuid


# Instructor model
class Instructor(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    full_time = models.BooleanField(default=True)
    total_learners = models.IntegerField()

    def __str__(self):
        return self.user.username


# Learner model
class Learner(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    STUDENT = 'student'
    DEVELOPER = 'developer'
    DATA_SCIENTIST = 'data_scientist'
    DATABASE_ADMIN = 'dba'
    OCCUPATION_CHOICES = [
        (STUDENT, 'Student'),
        (DEVELOPER, 'Developer'),
        (DATA_SCIENTIST, 'Data Scientist'),
        (DATABASE_ADMIN, 'Database Admin')
    ]
    occupation = models.CharField(
        null=False,
        max_length=20,
        choices=OCCUPATION_CHOICES,
        default=STUDENT
    )
    social_link = models.URLField(max_length=200)

    def __str__(self):
        return self.user.username + "," + \
               self.occupation


# Course model
class Course(models.Model):
    name = models.CharField(null=False, max_length=30, default='online course')
    image = models.ImageField(upload_to='course_images/')
    description = models.CharField(max_length=1000)
    pub_date = models.DateField(null=True)
    instructors = models.ManyToManyField(Instructor)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Enrollment')
    total_enrollment = models.IntegerField(default=0)
    is_enrolled = False

    def __str__(self):
        return "Name: " + self.name + "," + \
               "Description: " + self.description


# Lesson model
class Lesson(models.Model):
    title = models.CharField(max_length=200, default="title")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content = models.TextField()


# Enrollment model
# <HINT> Once a user enrolled a class, an enrollment entry should be created between the user and course
# And we could use the enrollment to track information such as exam submissions
class Enrollment(models.Model):
    AUDIT = 'audit'
    HONOR = 'honor'
    BETA = 'BETA'
    COURSE_MODES = [
        (AUDIT, 'Audit'),
        (HONOR, 'Honor'),
        (BETA, 'BETA')
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_enrolled = models.DateField(default=now)
    mode = models.CharField(max_length=5, choices=COURSE_MODES, default=AUDIT)
    rating = models.FloatField(default=5.0)

    # Used to persist question content for a course
class Question(models.Model):
    # Has a One-To-Many (or Many-To-Many if you want to reuse questions) relationship with course
    course = models.ForeignKey(Course, default=None, on_delete=models.CASCADE)
    # question text content     # Has question content
    content = models.TextField(max_length=500, default="title")
    # Has a grade point for each question   # question grade/mark # Has a grade point for each question
    grade = models.FloatField(default=0)
    # Foreign key to lesson
    lesson_id = models.ForeignKey(Lesson, on_delete=models.CASCADE)

    # A sample model method to calculate if learner get the score of the question
    def is_get_score(self, selected_ids):
       all_answers = self.choice_set.filter(is_correct=True).count()
       selected_correct = self.choice_set.filter(is_correct=True, id__in=selected_ids).count()
       if all_answers == selected_correct:
           return True
       else:
           return False

    def __str__(self):
        return self.content 

class Choice(models.Model):
    # One-To-Many (or Many-To-Many if you want to reuse choices) relationship with Question Choice content
    question = models.ForeignKey(Question, default=None, on_delete=models.CASCADE)
    content = models.TextField(max_length=100, default="title")
    # Indicate if this choice of the question is a correct one or not
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.content 

class Submission(models.Model):
   enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
   choices = models.ManyToManyField(Choice)

onlinecourse/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# <HINT> Import any new Models here
from .models import Course, Enrollment, Question, Choice, Submission, Lesson
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth import login, logout, authenticate
import logging
# Get an instance of a logger
logger = logging.getLogger(__name__)
# Create your views here.


def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'onlinecourse/user_registration_bootstrap.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("onlinecourse:index")
        else:
            context['message'] = "User already exists."
            return render(request, 'onlinecourse/user_registration_bootstrap.html', context)


def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('onlinecourse:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'onlinecourse/user_login_bootstrap.html', context)
    else:
        return render(request, 'onlinecourse/user_login_bootstrap.html', context)


def logout_request(request):
    logout(request)
    return redirect('onlinecourse:index')


def check_if_enrolled(user, course):
    is_enrolled = False
    if user.id is not None:
        # Check if user enrolled
        num_results = Enrollment.objects.filter(user=user, course=course).count()
        if num_results > 0:
            is_enrolled = True
    return is_enrolled


# CourseListView
class CourseListView(generic.ListView):
    template_name = 'onlinecourse/course_list_bootstrap.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        user = self.request.user
        courses = Course.objects.order_by('-total_enrollment')[:10]
        for course in courses:
            if user.is_authenticated:
                course.is_enrolled = check_if_enrolled(user, course)
        return courses


class CourseDetailView(generic.DetailView):
    model = Course
    template_name = 'onlinecourse/course_detail_bootstrap.html'


def enroll(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    user = request.user

    is_enrolled = check_if_enrolled(user, course)
    if not is_enrolled and user.is_authenticated:
        # Create an enrollment
        Enrollment.objects.create(user=user, course=course, mode='honor')
        course.total_enrollment += 1
        course.save()

    return HttpResponseRedirect(reverse(viewname='onlinecourse:course_details', args=(course.id,)))


# <HINT> Create a submit view to create an exam submission record for a course enrollment,
# you may implement it based on following logic:
         # Get user and course object, then get the associated enrollment object created when the user enrolled the course
         # Create a submission object referring to the enrollment
         # Collect the selected choices from exam form
         # Add each selected choice object to the submission object
         # Redirect to show_exam_result with the submission id
def submit(request, course_id):
    user = request.user
    course = Course.objects.get(pk=course_id)
    enrollment = Enrollment.objects.get(user=user, course=course)
    submitted_anwsers = extract_answers(request)
    submission = Submission.objects.create(enrollment=enrollment)
    submission.choices.set(submitted_anwsers)
    print(submission)
    return  HttpResponseRedirect(reverse(viewname='onlinecourse:result', args=(course_id, submission.choices.first().question.lesson.pk, submission.pk)))

# <HINT> A example method to collect the selected choices from the exam form from the request object
def extract_answers(request):
   submitted_anwsers = []
   for key in request.POST:
       if key.startswith('choice'):
           value = request.POST[key]
           choice_id = int(value)
           submitted_anwsers.append(choice_id)
   return submitted_anwsers


# <HINT> Create an exam result view to check if learner passed exam and show their question results and result for each question,
# you may implement it based on the following logic:
        # Get course and submission based on their ids
        # Get the selected choice ids from the submission record
        # For each selected choice, check if it is a correct answer or not
        # Calculate the total score
def show_exam_result(request, course_id, lesson_id, submission_id):
    from django.db.models import Sum
    course = Course.objects.get(pk=course_id)
    submission = Submission.objects.get(pk=submission_id)
    selected_choices = submission.choices.all()

    lesson = Lesson.objects.get(pk=lesson_id)
    questions = lesson.question_set.all()
    total_mark = round(lesson.question_set.all().aggregate(Sum("grade"))["grade__sum"])
    grade = 0
    for question in questions:
        if question.is_get_score(selected_choices):
            grade += question.grade

    context = {
        'grade': round(grade),
        'total_mark': total_mark,
        'questions': questions,
        'lesson': lesson,
        'selected_choices': selected_choices,
    }

    return render(request , 'onlinecourse/exam_result_bootstrap.html' , context)

templates/onlinecourse/course_details_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Page content -->
    <div class="container-fluid">
            <h2>{{ course.name }}</h2>
            <div class="card-columns-vertical">
                {% for lesson in course.lesson_set.all %}
                    <div class="card mt-1">
                        <div class="card-header"><h5>Lesson {{lesson.order|add:1}}: {{lesson.title}}</h5></div>
                        <div class="card-body">{{lesson.content}}</div>
                    </div>
                {% endfor %}
            </div>
    <!-- Task: show questions and choices -->
            <!-- <HINT> Use Bootstrap Collapse to hide exam first, more details could be found here
            https://www.w3schools.com/bootstrap4/bootstrap_collapse.asp-->

            <!--
            A collapse example here:
            <div id="exam" class="collapse">
                Click to expand elements within the collapse div
                </div>
            -->
            <button data-toggle="collapse" data-target="#exam"
                 class="btn btn-info" role="button" style="width:100%">
                Start Exam</button>

            <div id="exam" class="collapse">
                 {% if user.is_authenticated %}
                    <form id="questionform" action="{% url 'onlinecourse:submit' course.id %}" method="post">
                         {% for question in course.question_set.all %}
                        <div class="card mt-1">
                            <div class="card-header">
                                <h5>{{question.title}}</h5>
                            </div>
                            {% csrf_token %}
                            <b>{{question.text}}</b><br/>
                            <div class="form-group">
                                {% for choice in question.choice_set.all %}
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="checkbox" name="choice_{{choice.id}}"
                                                class="form-check-input" id="{{choice.id}}"
                                                value="{{choice.id}}">{{ choice.text }}
                                        </label>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>                        
                        {% endfor %}
                         <input class="btn btn-success btn-block" type="submit" value="Submit">
                    </form>       
                 {% endif %}
            </div>
            <!-- <HINT> If user is authenticated, show course exam with a list of question -->

            <!-- <HINT> Each example will have many questions -->

            <!-- <HINT> Each question will have many choices -->


            <!-- <HINT> Create a form to collect the selected choices for all questions -->
            <!-- <HINT> For each question choice, you may create a checkbox input like
            <input type="check" name="choice_{{choice.id}}" id="{{choice.id}}" ...>
            -->

            <!-- A choice submission form example
            <form id="questionform" action="point to a submit view" method="post">
                        ... for each question in the course ...
                        <div class="card mt-1">
                            <div class="card-header"><h5>{{ question.question_text}}</h5></div>
                            {% csrf_token %}
                            <div class="form-group">
                               ... for each choice in the question ...
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input type="checkbox" name="choice_{{choice.id}}"
                                               class="form-check-input" id="{{choice.id}}"
                                               value="{{choice.id}}">{{ choice.choice_text }}
                                    </label>
                                </div>
                            </div>
                        </div>
                    <input class="btn btn-success btn-block" type="submit" value="Submit">
            </form> -->

            <!--Check here to see more details Bootstrap checkbox
             https://www.w3schools.com/bootstrap4/bootstrap_forms_inputs.asp-->
    </div>
</body>
</html>

templates/onlinecourse/exam_result_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

 <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
                <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Username" name="username" >
                        <input type="password" class="form-control" placeholder="Username" name="psw" >
                        <button class="btn btn-primary" type="submit">Login</button>
                        <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                    </div>
                </form>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container-fluid">
    {% if grade > 80 %}
    <div class="alert alert-success">
       <!--HINT Display passed info -->
       <p><b>Congratulation, {{ user.username }}!</b> You have  passed the exam your score is {{grade}}/{{total_mark}}<p>
    </div>
        {% else %}
        <div class="alert alert-danger">
            <!--HINT Display failed info -->
                <p>Failed, {{ user.username }}! You have failed the exam your score is {{grade}}/{{total_mark}}<p>

        </div>
        <a class="btn btn-link text-danger" href="{% url 'onlinecourse:course_details' lesson.course.id %}">Re-test</a>
        {% endif %}
        <div class="card-columns-vertical mt-1">
        <h5 class="">Exam results</h5>
            <!--HINT Display exam results-->
            {% for question in questions %}
            <div class="card mt-1">
                <div class="card-header"><h5>{{ question }}</h5></div>
                <div class="card-body">
                    {% for choice in question.choice_set.all %}
                        {% if choice in selected_choices %}
                            {% if choice.is_correct%}
                                <p class="alert alert-success">{{choice}}<p>
                            {% else %}
                                <p class="alert alert-danger">{{choice}}<p>
                            {% endif %}
                        {% else %}
                            {% if choice.is_correct %}
                                <p class="alert alert-warning">{{choice}}--unselected correct answer<p>
                            {% else %}
                                <p>{{choice}}<p>
                            {% endif %}
                            
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>